
server:
  port: 4399
# 嵌入式数据库配置
spring:
  application:
    name: tripDemo
  datasource:
    url: jdbc:h2:file:~/userdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  mapper-locations: classpath*:com/skymmer/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# 图片存储配置
app:
  storage:
    imageDir: "D:/AAA/image"
    maxSizeMB: 10     # 最大图片大小
    allowedTypes: image/jpeg,image/png,image/tiff,image/webp,image/wav,image/avi,image/psd,image/bmp,image/gif,image/heif,image/raw,image/heic
    thumbnailDir: "D:/AAA/thumbnail"